### ISSUE TITLE
Test Wording

### ISSUE THREAD

**Issue by melissamcewen** [jdhines/gather-phase-4#2]
I always say that writing successful tests is 25% coding and 75% writing. Code gets them to work. But 90% of the time people won't look at the code, they'll only see the writing. I try to imagine a non-developer reading my tests. Would they understand the language? If not, I try to write them better and clearer.
https://github.com/jdhines/gather-phase-4/blob/126c3918254ea70fbd2d96a2e7e54958d6d2e560/test/routes/single-item-test.js#L19

You test is definitely correct in what it does but I think "renders item properties" is not very understandable unless you know the code really well. I would use "renders a single item" or something similar that expresses that what we are testing is seeing an item with the correct info.

**Comment by jdhines** [comment]
Thanks, clarity of wording is important to me too. Being that this was a tutorial, I didn't put as much thought into it as I should have (or do elsewhere). Fixed in 29af7ec.
